### ISSUE TITLE
Add support to hasura authorization

### ISSUE THREAD

**Issue by mihnsen** [axis-tech/hasura-auto-tracker#11]
Hasura allow you to set the admin secret to protected hasura endpoint.
So the hasura-auto-tracker will send post request to this endpoint without password now.
Should have an option:
`hasura-auto-tracker --hasuraEndpoint=ENDPOINT --hasuraAdminSecret=myadminsecretkey ...`

**Comment by mihnsen** [comment]
And it should be available in config file too

**Comment by chrisnurse** [comment]
Thanks for implementing Minh!
