### ISSUE TITLE
Update CLI to enable access to "untracking" feature

### ISSUE THREAD

**Issue by chrisnurse** [axis-tech/hasura-auto-tracker#7]
Refer to example/run-hat.js

The config now makes it possible to execute the configuration actions individually
e.g. execute untracking separately from tracking, just in case this proves useful

**Comment by chrisnurse** [comment]
Dario would you mind picking this one up please?

**Comment by dariocravero** [comment]
Hey @chrisnurse, sorry for the delay in answering. I'm pretty swamped with work and I don't think I'll manage to get on to doing this, so I'll remove myself from the assignees for the time being. Cheers!
